variables:
  PLUGIN: 'profilefield_coupon'
  PATHNAME: 'user/profile/field/coupon'
  REPOURL: 'https://github.com/sebsoftnl/moodle-profilefield_coupon'

include:
  - project: 'sebsoft/open-source/gitlab'
    file: '/opensource-plugin/opensource-plugin-405+.yml'
    ref: main
